/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'background':                'rgb(var(--color-background) / <alpha-value>)',
        'surface':                   'rgb(var(--color-surface) / <alpha-value>)',
        'surface-dim':               'rgb(var(--color-surface-dim) / <alpha-value>)',
        'surface-bright':            'rgb(var(--color-surface-bright) / <alpha-value>)',
        'surface-container-lowest':  'rgb(var(--color-surface-container-lowest) / <alpha-value>)',
        'surface-container-low':     'rgb(var(--color-surface-container-low) / <alpha-value>)',
        'surface-container':         'rgb(var(--color-surface-container) / <alpha-value>)',
        'surface-container-high':    'rgb(var(--color-surface-container-high) / <alpha-value>)',
        'surface-container-highest': 'rgb(var(--color-surface-container-highest) / <alpha-value>)',
        'surface-variant':           'rgb(var(--color-surface-variant) / <alpha-value>)',
        'on-surface':                'rgb(var(--color-on-surface) / <alpha-value>)',
        'on-surface-variant':        'rgb(var(--color-on-surface-variant) / <alpha-value>)',
        'primary':                   'rgb(var(--color-primary) / <alpha-value>)',
        'on-primary':                'rgb(var(--color-on-primary) / <alpha-value>)',
        'primary-container':         'rgb(var(--color-primary-container) / <alpha-value>)',
        'on-primary-container':      'rgb(var(--color-on-primary-container) / <alpha-value>)',
        'primary-fixed':             'rgb(var(--color-primary-fixed) / <alpha-value>)',
        'primary-fixed-dim':         'rgb(var(--color-primary-fixed-dim) / <alpha-value>)',
        'secondary':                 'rgb(var(--color-secondary) / <alpha-value>)',
        'on-secondary':              'rgb(var(--color-on-secondary) / <alpha-value>)',
        'secondary-container':       'rgb(var(--color-secondary-container) / <alpha-value>)',
        'on-secondary-container':    'rgb(var(--color-on-secondary-container) / <alpha-value>)',
        'outline':                   'rgb(var(--color-outline) / <alpha-value>)',
        'outline-variant':           'rgb(var(--color-outline-variant) / <alpha-value>)',
        'error':                     'rgb(var(--color-error) / <alpha-value>)',
        'on-error':                  'rgb(var(--color-on-error) / <alpha-value>)',
        'error-container':           'rgb(var(--color-error-container) / <alpha-value>)',
        'on-error-container':        'rgb(var(--color-on-error-container) / <alpha-value>)',
        'inverse-surface':           'rgb(var(--color-inverse-surface) / <alpha-value>)',
        'inverse-on-surface':        'rgb(var(--color-inverse-on-surface) / <alpha-value>)',
        'inverse-primary':           'rgb(var(--color-inverse-primary) / <alpha-value>)',
        'surface-tint':              'rgb(var(--color-surface-tint) / <alpha-value>)',
        'tertiary':                  'rgb(var(--color-tertiary) / <alpha-value>)',
        'tertiary-container':        'rgb(var(--color-tertiary-container) / <alpha-value>)',
        'on-tertiary':               'rgb(var(--color-on-tertiary) / <alpha-value>)',
      },
      fontFamily: {
        'display-lg':  ['Hanken Grotesk', 'sans-serif'],
        'headline-md': ['Hanken Grotesk', 'sans-serif'],
        'body-main':   ['Inter', 'sans-serif'],
        'body-sm':     ['Inter', 'sans-serif'],
        'mono-data':   ['Geist', 'monospace'],
        'label-caps':  ['Geist', 'monospace'],
      },
      fontSize: {
        'display-lg':  ['48px', { lineHeight: '1.1',  letterSpacing: '-0.03em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.2',  letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-main':   ['16px', { lineHeight: '1.6',  letterSpacing: '-0.01em', fontWeight: '400' }],
        'body-sm':     ['14px', { lineHeight: '1.5',  letterSpacing: '0em',     fontWeight: '400' }],
        'mono-data':   ['14px', { lineHeight: '1.4',  letterSpacing: '-0.01em', fontWeight: '400' }],
        'label-caps':  ['12px', { lineHeight: '1',    letterSpacing: '0.05em',  fontWeight: '600' }],
      },
      spacing: {
        'xs': '4px', 'sm': '8px', 'md': '16px',
        'lg': '24px', 'xl': '40px',
        'gutter': '24px', 'unit': '4px',
      },
      borderRadius: {
        DEFAULT: '12px', 'lg': '12px', 'xl': '16px', 'full': '9999px',
      },
    },
  },
  plugins: [],
}
